module.exports = {
  out: process.cwd(),
  root: '',
  delay: 0,
  selector: '',
  'zoom-factor': 1,
  host: 'localhost',
  port: 3000,
  format: 'png',
  quality: 75,
  'user-agent': '',
  'cookie': '',
  latency: null,
  download: null,
  upload: null,
  filename: '',
  'pdf-margin': 'default',
  'pdf-background': false,
  js: '',
  css: '',
  debug: false,

  // these are mostly used to figure out what options are unknown and hence should be passed to Chrome
  version: false,
  v: false,
  help: false,
  h: false,
};
